version: '3.4'

networks:
  iexec-net:
    driver: bridge

volumes:
  mysql-data:
    name: iexec-data

services:
  scheduler:
    image: iexechub/server:${SCHEDULER_DOCKER_IMAGE_VERSION}
    container_name: iexecscheduler
    hostname: iexecscheduler
    ports:
      - 4321:4321
      - 4322:4322
      - 4323:4323
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CERTIFICATE_AND_PRIVATE_KEYS_REPO}:/iexec/keystore
      - ${SCHEDULER_PERSISTING_FOLDER}:/var/xwhep
    networks:
      - iexec-net
    env_file:
      - containerEnvironment
    restart: unless-stopped

  worker:
    image: iexechub/worker:${WORKER_DOCKER_IMAGE_VERSION}
    container_name: iexecworker
    environment:
      - SCHEDULER_IP=scheduler
      - SCHEDULER_DOMAIN=iexecscheduler
      - TMPDIR=${RESULTS_FOLDER}
    ports:
      - 4321
      - 4322
      - 4323
      - 443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${RESULTS_FOLDER}:${RESULTS_FOLDER}
    networks:
      - iexec-net
    restart: unless-stopped

  gmond:
    image: gmond
    container_name: iexecgmond
    ports:
      - 8694:8694
    networks:
      - iexec-net

  gmetad:
    image: gmetad-gangliaweb
    volumes:
      - /etc/ganglia/gmetad.conf:/etc/ganglia/gmetad.conf
      - /var/lib/ganglia:/var/lib/ganglia
    ports:
      - 80:80
    networks:
      - iexec-net
  
  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER_LOGIN}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - iexec-net

  db-viewer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - iexec-net

