version: '3.4'

networks:
  xtremweb-net:
    driver: bridge

volumes:
  mysql-data:
    name: xtremweb-data

services:
  scheduler:
    image: iexechub/server:${SCHEDULER_DOCKER_IMAGE_VERSION}
    container_name: xwscheduler
    hostname: xwscheduler
    ports:
      - 4321:4321
      - 4322:4322
      - 4323:4323
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CERTIFICATE_AND_PRIVATE_KEYS_REPO}:/xwhep/keystore
    networks:
      - xtremweb-net
    env_file:
      - containerEnvironment
    restart: unless-stopped

  worker:
    image: iexechub/worker:${WORKER_DOCKER_IMAGE_VERSION}
    container_name: xwworker
    environment:
      - SCHEDULER_IP=scheduler
      - SCHEDULER_DOMAIN=xwscheduler
      - TMPDIR=${RESULTS_FOLDER}
    ports:
      - 4321
      - 4322
      - 4323
      - 443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${RESULTS_FOLDER}:${RESULTS_FOLDER}
    networks:
      - xtremweb-net
    restart: unless-stopped

  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER_LOGIN}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - xtremweb-net

  db-viewer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - xtremweb-net
